### ISSUE TITLE
Formatter adds requires when I'm using ES6 and import syntax

### ISSUE THREAD

**Issue by paymog** [facebook-atom/nuclide-format-js#66]
### Issue and Steps to Reproduce
I'm writing a react native app with ES6 using `import ...` syntax. When I run the formatter lots of `require(...)` statements are added as imports.

![image](https://user-images.githubusercontent.com/1986950/32088463-6042088c-ba98-11e7-9df3-e4d1d8727afc.png)

### Expected Behavior
the formatter should recognize that I'm not using require syntax and not add them

### Actual Behavior
lots of `require`s are added as imports

**Comment by paymog** [comment]
Well I feel silly, I looked at the settings and unchecked `Add missing requires`, `Format requires` and `remove unused requires`:
![image](https://user-images.githubusercontent.com/1986950/32088512-c36f9636-ba98-11e7-9026-7a2fe3b29023.png)

**Comment by kyldvs** [comment]
Yeah this module is actually terribly named :D (sorry), it doesn't really do much formatting at all. It's primary purpose is adding requires and sorting them. If you want code formatting you should try to use the prettier package.
