### ISSUE TITLE
Failed to format code: No code formatting providers found!

### ISSUE THREAD

**Issue by HeidernBuffalo** [facebook-atom/nuclide-format-js#73]
### Issue and Steps to Reproduce
- Installed nuclide server and client version 0.288.0. nuclide-format-js 0.0.45 is installed.
- On a Mac, in Atom open a remote React.js project on devserver. 
- Open any .js file.
- Press cmd-shift-i, the auto-acquire function works perfectly.
- Press cmd-shift-c to reformat the code.

### Expected Behavior
The code gets formatted.

### Actual Behavior
Message pops out: `Failed to format code: No code formatting providers found!`

**Comment by kyldvs** [comment]
This package is unfortunately named, it doesn't do any code formatting. Just the auto-require functionality. (It originally had more lofty goals!)

Instead you should use https://prettier.io/ for code formatting.

**Comment by trusktr** [comment]
I don't have `nuclide-format-js` installed, but I still see the "Code Format: Format Code" command (and the same error described here) so I don't think it is related to this package.
